bc-api-key: 43cd09f6-360b-44f7-b603-9e0d56c9bdf2::TlH8Q8YLRVFlIgFuosAdlsWUKhg=
block-list-secret-scan: []
branch: master
custom-tool-name: Checkov
directory:
- ./
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- - sca_package
mask: []
prisma-api-url: https://api0.prismacloud.io
repo-id: kjackson03/codegoat_azure
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
- CKV_CVE_2023_30861
soft-fail: true
summary-position: top
