bc-api-key: $(BC_API_KEY)
block-list-secret-scan: []
branch: master
custom-tool-name: Checkov
directory:
- ./sca-package
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- - sca_package
mask: []
prisma-api-url: $(PRISMA_API_URL)
repo-id: kjackson03/codegoat_azure
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
- CKV_CVE_2023_30861
soft-fail: true
summary-position: top